"""Render layer for the adapters: validated slot answers + contracts.yaml -> pipeline/ files.

    from builder_agent.render import render_adapters
    result = render_adapters(ctx, contracts, slot_answers, out_root=repo_path)
    assert result.ok, result.lint

No LLM here. Slot answers are validated against scanner facts first; every
rendered .py file is checked with pyflakes and every .json file is parsed.
Files are only (re)written if the Builder generated them and nobody edited them.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
from pathlib import Path, PurePosixPath

from jinja2 import Environment, PackageLoader, StrictUndefined
from pydantic import BaseModel
from pyflakes.api import check as pyflakes_check
from pyflakes.reporter import Reporter

from ..decide.contracts import Contracts
from ..scan.models import RepoContext
from .slots import SlotAnswers, slot_candidates, validate_slots

__all__ = ["render_adapters", "lint_files", "RenderError", "RenderResult",
           "SlotAnswers", "slot_candidates", "validate_slots"]

ADAPTERS = ["train.py", "evaluate.py", "serve.py", "data.py", "sample_request.json"]
MARKER = "# Generated by builder-agent. Do not edit by hand: regenerate."
MANIFEST = ".builder-manifest.json"
SUPPORTED_METRICS = {"rmse", "mae", "r2"}
FORWARD = {"log1p": "np.log1p", "log": "np.log"}
INVERSE = {"log1p": "np.expm1", "log": "np.exp"}
# arg_map tokens -> expression in train.py
TOKEN_EXPR = {"$train_path": "train_path", "$train_df": "df", "$X": "X", "$y": "y", "$target_column": "TARGET"}


class RenderError(Exception):
    pass


class RenderResult(BaseModel):
    files: list[str]               # repo-relative paths written
    lint: list[str]                # pyflakes / JSON problems; empty when clean

    @property
    def ok(self) -> bool:
        return not self.lint


def _env() -> Environment:
    env = Environment(loader=PackageLoader("builder_agent.render", "templates"),
                      undefined=StrictUndefined, keep_trailing_newline=True,
                      trim_blocks=True, lstrip_blocks=True)
    env.filters["py"] = py_literal
    env.filters["tojson_pretty"] = lambda v: json.dumps(v, indent=2)
    env.filters["json"] = json.dumps   # unlike jinja's tojson, no HTML escaping of quotes
    return env


def py_literal(value, width: int = 80) -> str:
    """A Python literal for generated code: double-quoted strings, long lists one item per line."""
    if isinstance(value, str):
        return json.dumps(value)                  # a JSON string is also a valid Python string
    if isinstance(value, (list, tuple)):
        items = [py_literal(v) for v in value]
        one_line = "[" + ", ".join(items) + "]"
        if len(one_line) <= width:
            return one_line
        return "[\n" + "".join(f"    {i},\n" for i in items) + "]"
    if isinstance(value, (bool, int, float)) or value is None:
        return repr(value)
    raise TypeError(f"no Python literal for {type(value).__name__}")


def _coerce(value: str):
    if value in ("True", "False"):
        return value == "True"
    for cast in (int, float):
        try:
            return cast(value)
        except ValueError:
            pass
    return value


def _first_record(root: Path, path: str, features: list[str]) -> dict:
    """Row 1 of a data file, features only, typed like pandas would read them."""
    with open(root / path, encoding="utf-8-sig", newline="") as f:
        row = next(csv.DictReader(f), None)
    if row is None:
        raise RenderError(f"{path} has a header but no rows; can't build sample_request.json")
    return {c: _coerce(row[c]) for c in features}


def template_context(ctx: RepoContext, c: Contracts, s: SlotAnswers) -> dict:
    adapters_dir = c.paths["adapters_dir"].strip("/")
    headers = {d.path: d.columns for d in ctx.data_columns}
    features = [col for col in headers[s.train.train_file] if col != s.target_column]

    fmt = (c.model_extra or {}).get("formats", {}).get("eval_report", {})
    unsupported = set(fmt.get("metrics", {})) - SUPPORTED_METRICS
    if unsupported:
        raise RenderError(f"contracts.yaml formats.eval_report.metrics asks for {sorted(unsupported)}; "
                          f"evaluate.py.j2 supports {sorted(SUPPORTED_METRICS)}")
    endpoints = c.serving.endpoints
    if "predict" not in endpoints or "health" not in endpoints:
        raise RenderError("contracts.yaml serving.endpoints needs 'predict' and 'health'")
    response = (c.serving.model_extra or {}).get("response", {})

    module, fn_name = s.train.train_function.split(":")
    tokens = {v for v in s.train.arg_map.values() if isinstance(v, str)}
    call_args = ", ".join(f"{k}={TOKEN_EXPR[v] if isinstance(v, str) and v in TOKEN_EXPR else repr(v)}"
                          for k, v in s.train.arg_map.items())
    uses_y = "$y" in tokens
    forward = FORWARD.get(s.target_transform) if uses_y and not s.transform_inside_train_fn else None

    data_module, data_fn = (s.data.data_step.split(":") if s.data.data_step != "existing" else (None, None))

    return {
        "marker": MARKER,
        "adapters_dir": adapters_dir,
        "depth": len(PurePosixPath(adapters_dir).parts),
        "app_target": f"{adapters_dir.replace('/', '.')}.serve:app",
        # shared slots
        "target": s.target_column,
        "features": features,
        "transform": s.target_transform,
        "inverse_fn": INVERSE.get(s.target_transform),
        "flavor": s.model_flavor,
        "model_input": s.model_input,
        # train
        "fn_module": module,
        "fn_name": fn_name,
        "train_file": s.train.train_file,
        "call_args": call_args,
        "uses_train_path": "$train_path" in tokens,
        "uses_x": "$X" in tokens,
        "uses_y": uses_y,
        "y_forward_fn": forward,
        # evaluate
        "eval_file": s.evaluate.eval_file,
        "group_column": s.evaluate.group_column,
        # data
        "data_step": s.data.data_step,
        "data_fn_module": data_module,
        "data_fn_name": data_fn,
        "required_files": list(dict.fromkeys([s.train.train_file, s.evaluate.eval_file])),
        # serve
        "sample_record": _first_record(Path(ctx.root), s.evaluate.eval_file, features),
        "port": c.serving.port,
        "predict_path": endpoints["predict"].path,
        "predict_method": endpoints["predict"].method.upper(),
        "health_path": endpoints["health"].path,
        "health_method": endpoints["health"].method.upper(),
        "prediction_field": response.get("prediction_field", "prediction"),
        "version_field": response.get("model_version_field", "model_version"),
        # contract values
        "sample_var": c.sample_mode.variable,
        "fraction": c.sample_mode.fraction,
        "mlflow_uri": c.paths["mlflow_uri"],
        "experiment": c.paths["mlflow_experiment"],
        "model_uri_env": c.serving.model_uri_env,
        "model_uri_file": c.paths["latest_model_uri"],
        "eval_report": c.paths["eval_report"],
        "predictions_log": c.paths["predictions_log"],
    }


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def write_guarded(out_root: Path, manifest_rel: str, files: dict[str, str]) -> None:
    """Write files (repo-relative path -> text) and record their hashes in the manifest.

    Never overwrites a file the Builder didn't write, or one that was edited since;
    in that case nothing at all is written.
    """
    manifest_path = out_root / manifest_rel
    manifest = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else {}
    known: dict[str, str] = manifest.get("files", {})
    for rel in files:
        path = out_root / rel
        if path.exists() and known.get(rel) != _sha(path.read_text(encoding="utf-8")):
            why = "was edited after the Builder wrote it" if rel in known else "was not generated by the Builder"
            raise RenderError(f"refusing to overwrite {rel}: it {why}")
    for rel, text in files.items():
        path = out_root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
    known.update({rel: _sha(text) for rel, text in files.items()})
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps({"files": dict(sorted(known.items()))}, indent=2) + "\n",
                             encoding="utf-8", newline="\n")


def manifest_path(contracts: Contracts) -> str:
    return f"{contracts.paths['adapters_dir'].strip('/')}/{MANIFEST}"


def render_adapters(ctx: RepoContext, contracts: Contracts, answer: dict | SlotAnswers,
                    out_root: str | Path) -> RenderResult:
    """Validate, render every adapter, write them under out_root/<adapters_dir>, lint them."""
    v = validate_slots(ctx, answer)
    if not v.ok:
        raise RenderError("invalid slot answers: " + "; ".join(v.reasons))
    tctx = template_context(ctx, contracts, v.slots)
    env = _env()
    rendered = {f"{tctx['adapters_dir']}/{name}": env.get_template(f"{name}.j2").render(**tctx)
                for name in ADAPTERS}
    out_root = Path(out_root)
    write_guarded(out_root, manifest_path(contracts), rendered)
    files = list(rendered)
    return RenderResult(files=files, lint=lint_files(out_root, files))


def lint_files(root: str | Path, files: list[str]) -> list[str]:
    """pyflakes on .py files, json.loads on .json files. Returns problems, one per line."""
    root = Path(root)
    out, err = io.StringIO(), io.StringIO()
    reporter = Reporter(out, err)
    problems: list[str] = []
    for rel in files:
        text = (root / rel).read_text(encoding="utf-8")
        if rel.endswith(".py"):
            pyflakes_check(text, rel, reporter)
        elif rel.endswith(".json"):
            try:
                json.loads(text)
            except json.JSONDecodeError as e:
                problems.append(f"{rel}: invalid JSON: {e}")
    problems += [line for line in (out.getvalue() + err.getvalue()).splitlines() if line.strip()]
    return problems
